import React from 'react';

import Description from './Components/Description';
import Products from './Components/Products';
import Title from './Components/Tittle';

const products = [
  { id: 1, title: 'Californication (Deluxe Edition) 1', description: 'Californication é o sétimo álbum de estúdio da banda norte-americana de rock Red Hot Chili Peppers. Produzido por Rick Rubin e lançado em 8 de Junho de 1999 pela Warner Bros. Records, Californication', image: 'urlhttps://th.bing.com/th/id/OIP.wu7OQJ70xXa2Hy9EDUhXdwAAAA?rs=1&pid=ImgDetMain-da-imagem-1' },
  { id: 2, title: 'Black Sabbath, Vol. 4 (Remastered) 2', description: 'l. 4 é o quarto álbum de estúdio da banda britânica de heavy metal Black Sabbath, lançado em 1972. O título original do álbum seria Snowblind, que faz referência ao uso de cocaína, mas a gravadora não os deixou manter o título, pois naqueles dias a cocaína era um problema sério e eles não queriam causar polêmica. Então o título Snowblind foi descartado e o quarto álbum foi intitulado apenas como Vol. 4. Em 2017, foi eleito o 14º melhor álbum de metal de todos os tempos pela revista Rolling Stone', image: 'url-da-https://th.bing.com/th/id/OIP.9Tl_OILLtW1ftxrZfKXyRQHaHa?rs=1&pid=ImgDetMainimagem-2' },
  { id: 3, title: 'MM..FOOD ', description: 'Mm.. Food é o quinto álbum de estúdio do rapper e produtor anglo-americano MF Doom, lançado pela Rhymesayers em novembro de 2004. O álbum alcançou a posição 17 na parada de álbuns independentes', image: 'https://th.bing.com/th/id/OIP.5djQgMmCuQ8IrMy-WcB-xQHaHa?rs=1&pid=ImgDetMain' },
  { id: 4, title: 'The College Dropout', description: 'The College Dropout é o álbum de estréia do artista americano de hip-hop Kanye West, lançado em 10 de fevereiro de 2004, pela Roc-A-Fella Records. Foi gravado durante um período de quatro anos, começando em 1999.', image: 'https://www.slantmagazine.com/wp-content/uploads/2018/05/collegedropout.jpg' },
  { id: 5, title: 'The Dark Side Of The Moon (50th Anniversary) [2023 Remaster]', description: 'The Dark Side of the Moon é o oitavo álbum de estúdio da banda britânica de rock progressivo Pink Floyd, lançado em 1 de março de 1973 através da Harvest Records no Reino Unido', image: 'url-da-imagem-1' },
  { id: 6, title: 'Blood Sugar Sex Magik', description: 'Blood Sugar Sex Magik é o quinto álbum de estúdio da banda estadunidense de rock Red Hot Chili Peppers, lançado no dia 24 de setembro de 1991, sendo um dos mais aclamados álbuns do rock alternativo. Foi produzido por Rick Rubin e é o primeiro trabalho da banda lançado pela Warner Bros. Records.', image: 'https://1.bp.blogspot.com/-6N21PNw2toM/VCI5gq5-9tI/AAAAAAAAOVY/MEaqpoNPqJc/s1600/Blood%2BSugar%2BSex%2BMagik.jpgurl-da-imagem-1' },
  { id: 7, title: 'Stankonia', description: 'Stankonia é o quarto álbum de estúdio da banda OutKast, lançado a 31 de Outubro de 2000 pela LaFace Records. O álbum estreou no número 2 na Billboard 200 nos EUA, vendendo mais de 530,000 cópias', image: 'https://th.bing.com/th/id/OIP.I714A4nSnvpdDbSN_SFzAwHaHa?rs=1&pid=ImgDetMain' },
  { id: 8, title: 'Straight Outta Compton 1', description: 'Straight Outta Compton é o álbum de estréia do grupo de gangsta rap N.W.A, lançado em 8 de agosto de 1988. A produção ocorreu principalmente com Dr. Dre e DJ Yella na co-produção.', image: 'https://th.bing.com/th/id/R.9d0610daf87218162b14cfdfad8242e6?rik=yva7CsRS%2bzVxCA&riu=http%3a%2f%2fwww.hiphopmusichistory.com%2fwp-content%2fuploads%2f2019%2f07%2fNWA-Straight-Outta-Compton-Album-Cover-1.jpg&ehk=JlRhE9RuWpyrMgE4%2fP%2fMsUedMdN2TNXo065DRLJMeZo%3d&risl=&pid=ImgRaw&r=0' },
  { id: 9, title: 'Sobrevivendo no Inferno', description: 'Sobrevivendo no Inferno é o segundo álbum de estúdio do grupo brasileiro de rap Racionais MCs. Foi lançado pelo selo da gravadora Cosa Nostra em 20 de dezembro de 1997.', image: 'https://th.bing.com/th/id/OIP.YvavvEO4aOblD1J1vpa3pQHaHZ?rs=1&pid=ImgDetMain' },
  { id: 10, title: 'Rap É Compromisso', description: 'Rap é Compromisso é o primeiro álbum de estúdio do artista musical brasileiro Sabotage e único lançado em vida, lançado em 2000 inicialmente pela gravadora Cosa Nostra, pertecente ao grupo Racionais MCs.', image: 'https://th.bing.com/th/id/OIP.OmlB6MzMjY4Hv3HdmYTpvQAAAA?rs=1&pid=ImgDetMain' },
  { id: 11, title: 'versos sangrentos', description: 'Versos Sangrentos do Facção Central é mais do que um simples álbum de rap - é uma crônica contundente da realidade das ruas, uma voz para os marginalizados e uma chamada à ação. Com letras afiadas e batidas poderosas, este álbum transcende os limites do gênero, oferecendo uma narrativa penetrante e visceral sobre as injustiças sociais e as lutas diárias enfrentadas pelas comunidades ', image: 'https://th.bing.com/th/id/OIP.nQ8_exhk3Cj7y2ZHySJLFgHaHa?rs=1&pid=ImgDetMain' },
  { id: 12, title: 'A Night at the Opera', description: 'A Night at the Opera é o quarto álbum de estúdio da banda britânica de rock Queen, lançado em 21 de novembro de 1975 na Europa e em 2 de dezembro de 1975 nas Américas. Nesse álbum, o Queen adotou uma sonoridade diferente comparada com seus discos anteriores, fazendo um uso ainda maior do piano', image: 'https://th.bing.com/th/id/OIP.n0ZIYkdmo71_aLkkkPKNjwHaHY?rs=1&pid=ImgDetMain' },
  { id: 13, title: 'Master of Puppets', description: 'Master of Puppets é o terceiro álbum de estúdio lançado pela banda de thrash metal/heavy metal norte-americana Metallica, lançado em 3 de março de 1986', image: 'url-da-imagem-1' },
  { id: 14, title: 'Mezmerize', description: 'Mezmerize é o quarto álbum de estúdio da banda armênia-estadunidense System of a Down. É a primeira parte do álbum duplo Mezmerize/Hypnotize. Foi lançado em 17 de Maio de 2005, seis meses antes de Hypnotize, pela American Recordings. O álbum já vendeu mais de 10 milhões de cópia no mundo inteiro', image: 'https://th.bing.com/th/id/OIP.4Kgfu6IV32ybVBeNh9WTWgHaHa?rs=1&pid=ImgDetMain' },
  { id: 15, title: 'Abbey Road', description: 'Abbey Road é o 12º álbum de estúdio da banda britânica The Beatles. Foi lançado em 26 de setembro de 1969, e leva o mesmo nome da rua de Londres onde situa-se o estúdio Abbey Road. Foi produzido e orquestrado por George Martin para a Apple Records. Este álbum está na lista dos 200 álbuns definitivos no Rock and Roll Hall of Fame.', image: 'https://i.pinimg.com/originals/e9/ce/fc/e9cefc3049a7362308a53e36b921d7cf.jpg' },
  { id: 16, title: 'Led Zeppelin II (Remastered)', description: 'Led Zeppelin II é o segundo álbum de estúdio da banda britânica de rock Led Zeppelin, lançado em 22 de outubro de 1969 pela Atlantic Records. As sessões de produção e gravação ', image: 'https://th.bing.com/th/id/R.ccee55ae0dad8e727b7a0294fadb90a1?rik=75tivW2jbr9FDw&riu=http%3a%2f%2f4.bp.blogspot.com%2f-x_NxyjxXCLg%2fUbmSC2krQBI%2fAAAAAAAAIOo%2fDLrNpKECwuM%2fs1600%2f%5bAllCDCovers%5d_led_zeppelin_led_zeppelin_ii_digitally_remastered_1994_retail_cd-front.jpg&ehk=RQY8zX6FCbhjhtOinrzQHVr9EugJwlZHkBIfwNrQC6A%3d&risl=&pid=ImgRaw&r=0' },
  { id: 17, title: 'Damn', description: 'Damn (estilizado como DAMN.) é o quarto álbum de estúdio do rapper estadunidense Kendrick Lamar. Foi lançado em 14 de abril de 2017, pelas editoras discográficas Top Dawg Entertainment, Aftermath Entertainment e Interscope Records. O disco teve a produção executiva executada por Anthony "Top Dawg" Tiffith, Dr. Dre, Sounwave, DJ Dahi, Mike Will Made It e Ricci Riera.', image: 'https://th.bing.com/th/id/R.c4c01ee3b36b92bf7307413dc5605ec6?rik=HvAEAGIH5X6qCg&pid=ImgRaw&r=0' },
  { id: 18, title: 'Graduation', description: 'Graduation é o terceiro álbum de estúdio do rapper estadunidense Kanye West. O seu lançamento ocorreu em 10 de setembro de 2007, através das gravadoras Roc-A-Fella Records e Def Jam Recordings. O disco possui uma sonoridade inspirada pela música eletrônica e a maioria de suas músicas', image: 'https://i.etsystatic.com/22331385/r/il/101d72/2521229938/il_1588xN.2521229938_9t9n.jpg' },
  { id: 19, title: 'Nevermind (Deluxe)', description: 'Nevermind é o segundo álbum de estúdio da banda estadunidense de rock Nirvana, lançado em 24 de setembro de 1991 pela DGC Records. Produzido por Butch Vig, foi o primeiro álbum de Nirvana a ser lançado pelo selo DGC, e o primeiro álbum da banda com a participação do baterista Dave Grohl. ', image: 'https://th.bing.com/th/id/R.b1bb3761835f7068f2a852301cecce61?rik=qY7Bh29sQi7k4w&pid=ImgRaw&r=0' },
  { id: 20, title: 'Dirt', description: 'Dirt é o segundo álbum de estúdio da banda de rock americana Alice in Chains, lançado em 29 de setembro de 1992 pela Columbia Records. As faixas "Would?", "Them Bones", "Angry Chair", "Rooster" e "Down in a Hole" foram lançadas como singles. Álbum que trouxe fama à banda, Dirt é lembrado por muitos como o magnum opus do Alice in Chains, e clássico da era de ouro ', image: 'https://th.bing.com/th/id/R.3d0dc2e11a760f16da62c901779c5081?rik=2lhWonSEIDYH1Q&pid=ImgRaw&r=0' },
  

  // Adicione mais produtos conforme necessário
];

const App = () => (
  <div>
    <Title>rtrtrt</Title>
    <Description>Confira nossos produtos abaixo</Description>
    <Products products={products} />
  </div>
);

export default App;
